spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /media/share/sourcecode/talk-talk/talk-parent/talk-config/config

server:
  port: 8771
