spring:
  application:
    name: talk-core

server:
  port: 10001
  
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8761/eureka/

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"