server:
  port: 10000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #        - id: core
        #          uri: lb://core
        #          predicates:
        #            - Path: /core/**
        #          filters:
        #            - name: Retry
        #              args:
        #                retries: 3

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8761/eureka/

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus